name: Tests
on:
  push:
    branches: [master]
  pull_request:
  schedule:
    # 16:21 UTC on Tuesdays
    - cron: "21 16 * * TUE"
  repository_dispatch:
    types: [tests]

env:
  DOCKER_BUILDKIT: 1
jobs:
  build-test:
    # https://wiki.postgresql.org/wiki/Apt only has packages for ubuntu LTS versions
    runs-on: ubuntu-22.04
    strategy:
      matrix:
#        postgresql: [10, 11, 12, 13, 14, 15]
        postgresql: [10]
    steps:
      - uses: actions/checkout@v3
      - name: Install PostgreSQL
        run: |
          echo | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
          # Optimization: only update 3rd party repos, not Ubuntu's own
          sudo apt-get install -y postgresql-${{ matrix.postgresql }} postgresql-server-dev-${{ matrix.postgresql }}
          # Force correct port
          # - sudo sed -Ei -e 's/^#?port =.+$/port = 5432/' /etc/postgresql/$PG/main/postgresql.conf
          # - sudo /etc/init.d/postgresql restart $PG
          # - sudo -u postgres createuser tests --superuser || true

      - name: Build
        run: |
          psql postgres -xA -c 'select version()'
          make
          sudo make install

      - name: Run installcheck
        run: |
          sudo pg_ctlcluster ${{ matrix.postgresql }} main start
          sudo pg_lsclusters
          make installcheck || (cat regression.diffs && false)
