name: Tests
on:
  push:
    branches: [master]
  pull_request:
  schedule:
    # 16:21 UTC on Tuesdays
    - cron: "21 16 * * TUE"
  repository_dispatch:
    types: [tests]

env:
  DOCKER_BUILDKIT: 1
jobs:
  build-test:
    # https://wiki.postgresql.org/wiki/Apt only has packages for ubuntu LTS versions
    runs-on: ubuntu-22.04
    strategy:
      matrix:
#        postgresql: [10, 11, 12, 13, 14, 15]
        postgresql: [10]
    steps:
      - uses: actions/checkout@v3
      - name: Install PostgreSQL
        run: |
          echo | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
          sudo apt-get install -y postgresql-${{ matrix.postgresql }} postgresql-server-dev-${{ matrix.postgresql }}
          # This is installed by default, get rid of it
          apt-get autoremove postgresql-server-dev-14

      - name: Build
        run: |
          make
          sudo make install

      - name: Run installcheck
        run: |
          sudo pg_ctlcluster ${{ matrix.postgresql }} main start
          sudo pg_lsclusters
          psql postgres -xA -c 'select version()'
          make installcheck || (cat regression.diffs && false)
