name: Tests
on:
  push:
    branches: [master]
  pull_request:
  schedule:
    # 16:21 UTC on Tuesdays
    - cron: "21 16 * * TUE"
  repository_dispatch:
    types: [tests]

env:
  DOCKER_BUILDKIT: 1
jobs:
  build-test:
    # https://wiki.postgresql.org/wiki/Apt only has packages for ubuntu LTS versions
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # Test with v14 first, for faster results: it's bundled already with GitHub image
        postgresql: [14, 10, 11, 12, 13, 15]
    steps:
      - uses: actions/checkout@v3
      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          # If needed, uninstall PostgreSQL v14 that GitHub supplies
          if test "${{ matrix.postgresql }}" != 14; then
              sudo pg_dropcluster 14 main --stop
              sudo apt-get remove postgresql-14 postgresql-client-14
              echo | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
          fi
          sudo apt-get install -y \
              postgresql-${{ matrix.postgresql }} \
              postgresql-server-dev-${{ matrix.postgresql }}

      - name: Build
        run: |
          make
          sudo make install

      - name: Run installcheck
        run: |
          sudo pg_ctlcluster ${{ matrix.postgresql }} main start
          sudo pg_lsclusters
          sudo -H -u postgres createuser runner --superuser
          psql postgres -xA -c 'select version()'
          make installcheck || (cat regression.diffs && false)
